float:
  any:
    hnswlib:
      docker-tag: ann-benchmarks-hnswlib
      module: ann_benchmarks.algorithms.hnswlib
      constructor: HnswLib
      base-args: ["@metric"]
      run-groups:
        efConstruction-100-M-4:
          arg-groups:
            - {"efConstruction": 100, "M": 4}
          query-args: [[10, 20, 40, 80, 120, 200, 400, 600, 800, 1000, 1500]]
        efConstruction-100-M-16:
          arg-groups:
            - {"efConstruction": 100, "M": 16}
          query-args: [[10, 20, 40, 80, 120, 200, 400, 600, 800, 1000, 1500]]
        efConstruction-100-M-32:
          arg-groups:
            - {"efConstruction": 100, "M": 32}
          query-args: [[10, 20, 40, 80, 120, 200, 400, 600, 800, 1000, 1500]]
        efConstruction-100-M-48:
          arg-groups:
            - {"efConstruction": 100, "M": 48}
          query-args: [[10, 20, 40, 80, 120, 200, 400, 600, 800, 1000, 1500]]
        efConstruction-300-M-4:
          arg-groups:
            - {"efConstruction": 300, "M": 4}
          query-args: [[10, 20, 40, 80, 120, 200, 400, 600, 800, 1000, 1500]]
        efConstruction-300-M-16:
          arg-groups:
            - {"efConstruction": 300, "M": 16}
          query-args: [[10, 20, 40, 80, 120, 200, 400, 600, 800, 1000, 1500]]
        efConstruction-300-M-32:
          arg-groups:
            - {"efConstruction": 300, "M": 32}
          query-args: [[10, 20, 40, 80, 120, 200, 400, 600, 800, 1000, 1500]]
        efConstruction-300-M-48:
          arg-groups:
            - {"efConstruction": 300, "M": 48}
          query-args: [[10, 20, 40, 80, 120, 200, 400, 600, 800, 1000, 1500]]
        efConstruction-500-M-4:
          arg-groups:
            - {"efConstruction": 500, "M": 4}
          query-args: [[10, 20, 40, 80, 120, 200, 400, 600, 800, 1000, 1500]]
        efConstruction-500-M-16:
          arg-groups:
            - {"efConstruction": 500, "M": 16}
          query-args: [[10, 20, 40, 80, 120, 200, 400, 600, 800, 1000, 1500]]
        efConstruction-500-M-32:
          arg-groups:
            - {"efConstruction": 500, "M": 32}
          query-args: [[10, 20, 40, 80, 120, 200, 400, 600, 800, 1000, 1500]]
        efConstruction-500-M-48:
          arg-groups:
            - {"efConstruction": 500, "M": 48}
          query-args: [[10, 20, 40, 80, 120, 200, 400, 600, 800, 1000, 1500]]
  euclidean: []
  angular: []
bit:
  hamming: []
  jaccard: []
